### PR TITLE
simplified steps

### PR DESCRIPTION
**Pull request by abuehrle**
@errordeveloper made a few changes. Let me know if this is what you had in mind?  @monadic

### CODE REVIEW

**Comment by abuehrle** [comment]
@errordeveloper also, should we provide an explanation of what are seeing when we run docker ps?

**Comment by abuehrle** [comment]
Do you think we also need a section on how to install this manually? like it's been done in the Amazon Docs?

**Comment by errordeveloper** [comment]
> should we provide an explanation of what are seeing when we run docker ps?

I think we could just state that "there are 3 app containers running along with the Weave services".

> Do you think we also need a section on how to install this manually? like it's been done in the Amazon Docs?

Well, I am thinking there should some explanation to how installation is done, which could even be done by means of commenting the code a tiny bit more, I am not sure if it's worth it to do in plain text.

**Comment by errordeveloper** [comment]
Overall, this looks good, the output of all the things was a bit too verbose.

**Comment by abuehrle** [comment]
@kpoplin I've tagged you to include you in this discussion.

**Comment by abuehrle** [comment]
@errordeveloper should do this merge request? or will you? thnks...

**Comment by abuehrle** [comment]
@errordeveloper Would you like me to merge this?

**Comment by errordeveloper** [comment]
Looks all good, let's try to just avoid including the output for commands, as for example the output of weave status changes and even has a version string, so it sprt of asks for being updated at times, while nothing else changes really...

**Comment by abuehrle** [comment]
Agreed.  We should though include some just so the user can see that they are doing things correctly. Also, it highlights the weave bits. Otherwise, all you see is Vagrant.

**Pull request merged**
