### PR TITLE
ECS: Fetch AMI ids from Scope docs

### PR DESCRIPTION
**Pull request by 2opremio**
Needed after https://github.com/weaveworks/integrations/pull/126 is merged

### CODE REVIEW

**Comment by abuehrle** [comment]
I've included the URL and anchor to the ami docs. I think we can delete the integrations docs.

Didn't see this PR and already updated it.

**Comment by 2opremio** [comment]
@abuehrle Why isn't this needed? the `setup.sh` script in guides still uses https://raw.githubusercontent.com/weaveworks/integrations/master/aws/ecs/README.md

See https://github.com/weaveworks/guides/blob/41f1f5a60d39d39b78f0e06e224a7c3bad30c4e8/aws-ecs/setup.sh#L4

**Comment by abuehrle** [comment]
I didn't realize the setup script uses that. Ok maybe we could just leave the table there?

**Comment by abuehrle** [comment]
Let me know what's best.

**Comment by 2opremio** [comment]
I am confused. this PR makes the setup scripture the table in the new location.

**Comment by abuehrle** [comment]
Aack sorry fons. Yes we need that.

**Pull request merged**
