### PR TITLE
[aws-ecs] Add warning about hosted Scope not being covered until we update the guide

### PR DESCRIPTION
**Pull request by 2opremio**

### CODE REVIEW

**Comment by 2opremio** [comment]
@kpoplin @abuehrle PTAL

**Comment by davkal** [comment]
screen shot 2015-10-15 at 10 30 44

The asterisks dont do it for me.

**Comment by davkal** [comment]
screen shot 2015-10-15 at 13 46 25

I still find a notice like this at the beginning of an article a bit confusing.

**Comment by abuehrle** [comment]
This is good to go @2opremio

**Comment by 2opremio** [comment]
@davkal @abuehrle Thanks a lot. How do you test the guides locally?

**Pull request merged**
