### PR TITLE
kubernetes with weave on coreos and azure

### PR DESCRIPTION
**Pull request by abuehrle**
@errordeveloper  here is the initial cut of this file.  Please read the intro section to see that I've pitched this correctly.  I am working on the diagram now. 

@pidster have a look when you get a chance. Anything we should include about weave and kubernetes here?

### CODE REVIEW

**Comment by abuehrle** [comment]
Should say that I probably need to add a reference for this example in here.

**Comment by abuehrle** [comment]
@kpoplin and @mjlodge  I added a better value proposition to the intro of this guide.  It's a newish guide for Kubernetes on CoreOS in Azure.  It's based on an example that Kubernetes themselves wrote a few months ago.  I have attempted to bring out the 'weave bits' and why weave is the only solution.

**Comment by kpoplin** [comment]
I like it @abuehrle - the only phrase I might tweak would be "Without Weave, implementing simple networking for your app across Kubernetes clusters can be involved."

When we had the discussion w/the Amazon folks on the ECS guide, I know they wanted to "soften up" the language about any AWS deficiencies, so probably the same here to be cautious of. But maybe "can be a complex [and/or time-consuming] process" -- ?

**Comment by abuehrle** [comment]
@kpoplin that's true.  It's actually more a limitation of Docker than it is Kubernetes, so I will think about how to rephrase that.

**Comment by errordeveloper** [comment]
> It's based on an example that Kubernetes themselves wrote a few months ago. 

I wrote it :)

**Comment by errordeveloper** [comment]
I will need to remove all the scripts and leave just the readme, i.e. squash the history, as there are too many files in `node_modules` that shouldn't be checked-in.

**Comment by errordeveloper** [comment]
Also, we will need `<link rel="canonical" href="...">` here, as the copy on the Kubernetes site should remain ranking well and our copy is just for convenience.

**Comment by abuehrle** [comment]
My apologies, @errordeveloper  I did not know that!  very good example.

**Comment by errordeveloper** [comment]
We shouldn't have merged this in the current state, as it checks in 4k random files :(

**Comment by abuehrle** [comment]
Please remove the files that don’t belong —sorry about that.  I can’t publish anything to the web anyway, as there are incomplete website changes sitting in staging at the moment.

**Pull request merged**
