### PR TITLE
[aws-ecs] Cover Scope Cloud in the guide

### LINKED ISSUE #101: [ECS] Document how to use Weave Scope as a cloud Service
http://blog.weave.works/2015/10/08/weave-the-fastest-path-to-docker-on-amazon-ec2-container-service/

### PR DESCRIPTION
**Pull request by 2opremio**
@abuehrle @kpoplin Please review

Fixes #101

### CODE REVIEW

**Comment by 2opremio** [comment]
@kpoplin @abuehrle PTAL

**Comment by abuehrle** [comment]
@2opremio I've updated your doc.   @kpoplin let me know if we have described it correctly at the beginning of the doc. Maybe it needs more?

**Comment by 2opremio** [comment]
We should also review the Scope terminology based on what we decide internally (hopefully we will have an answer tomorrow).

**Comment by abuehrle** [comment]
@2opremio this will be up to how marketing wants to refer to the product.  We need to be consistent here. I will wait for @kpoplin 's opinion on this. She's also reviewing the file.

**Comment by kpoplin** [comment]
Just made a few tiny edits, otherwise looks good. I'm going to add a comment to the email thread about naming conventions, leaving that part of the guide as-is for now...

**Comment by 2opremio** [comment]
@abuehrle  Sure, I am happy as long as we are consistent everywhere. Thanks a lot for the edits BTW.

**Pull request merged**
