### PR TITLE
Aws ecs edits

### PR DESCRIPTION
**Pull request by abuehrle**
done some editing on this file, and added an introduction.  With regards to weaveDNS and load-balancing, is it correct to say that it randomizes IP addresses? should we be using some other terminology? or is it really randomizing -- makes it sound a bit chaotic of which I'm sure it is not:  @tomwilkie @2opremio @errordeveloper 

please let me know if you want me to change anything in here. I am happy to do it!

Forgive my naivete, but I realize this is a valid load-balancing strategy, after looking it up. Still, do we want to explicitly say this, though?

### CODE REVIEW

**Comment by abuehrle** [comment]
@kpoplin hope you are able comment here

**Comment by tomwilkie** [comment]
Yes it randomises the order in which it returns address to achieve a simple form of load balancing.  I just added a extra paragraph to the docs to explain this: https://github.com/weaveworks/weave/pull/1256

**Comment by abuehrle** [comment]
Thanks for the references. I have updated the docs.

**Comment by abuehrle** [comment]
Added a value proposition to the beginning of document. Please have a look and correct anything you see wrong or incorrect.  @tomwilkie @2opremio @monadic  @kpoplin Probably needs another editing pass...

**Comment by kpoplin** [comment]
nope, I don't see anywhere to comment when I'm actually viewing the doc on
github...

On 4 August 2015 at 12:38, Anita Buehrle notifications@github.com wrote:

> @kpoplin https://github.com/kpoplin hope you are able comment here
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/weaveworks/guides/pull/23#issuecomment-127731033.

## 

Katie Poplin
Marketing & Communications
Weave http://weave.works/
Mobile: +1.404.414.1993

**Comment by kpoplin** [comment]
[CCing Anita by email b/c I don't know if my feedback is making it into
github (at least I can't see it)...]

In the first paragraph, does it make sense to say "apps scattered within
Docker containers"?

The next couple of paragraphs do an awesome job of providing context for
what pain Weave will solve. However, when you move on to introduce Weave,
the first thing said is "Weave uses default port numbers and looks up IP
addresses in DNS" -- this doesn't hit you in the face with how much
better/easier life will be now that you've found weave. Maybe something
like "With Weave, you won't need to write and maintain that extra code
required for manually mapping ports..."? Then move on to how Weave actually
facilitates this (keeping the rest of the paragraph as-is).

Really like how the intro includes what you'll need, it builds/flows nicely
into the hands-on work. Small detail, but I might pull the "15 minutes" out
of the bullet point list, as a separate sentence to conclude that section,
e.g. "It should take approximately 15 minutes to complete this exercise."

Finally, in the conclusion, is there anything we could add in terms of
another exercise, other docs, anything to keep the reader engaged if he's
interested in doing more?

Overall really nice IMO :)

On 5 August 2015 at 14:36, Anita Buehrle notifications@github.com wrote:

> Added a value proposition to the beginning of document. Please have a look
> and correct anything you see wrong or incorrect. @tomwilkie
> https://github.com/tomwilkie @2opremio https://github.com/2opremio
> @monadic https://github.com/monadic @kpoplin
> https://github.com/kpoplin Probably needs another editing pass...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/weaveworks/guides/pull/23#issuecomment-128156851.

## 

Katie Poplin
Marketing & Communications
Weave http://weave.works/
Mobile: +1.404.414.1993

**Comment by abuehrle** [comment]
Those are great suggestions @kpoplin I will implement and then send you a new cut.

**Comment by abuehrle** [comment]
@kpoplin added a few lines. Let me know if this is what you were thinking.

**Comment by kpoplin** [comment]
Only a couple tiny comments but otherwise this looks good to go IMO. Really nice!

Nitpick, in the intro paragraph change "amoungst" to "among". But my original question was very elementary, basically - are the apps themselves scattered among containers, or are the containers scattered among apps? 

After describing the problem, the update you made to simply add "requires no custom code" - YES! I might even go so far as to say:
"Weave requires no custom code, saving time in both upfront development and longer-term maintenance. Instead, Weave uses..." - if you think that's too marketing-ish, I won't be offended :)

Great job w/the conclusion "find out more" resource links. Wdyt, should we add this section to all existing/future docs?

**Comment by 2opremio** [comment]
@abuehrle @kpoplin Thanks a lot for the corrections and the comments. Is it ready to go from the _copy_ perspective?

**Comment by abuehrle** [comment]
I believe it is.  I implemented some of @kpoplin suggestions.  thnks.  We can always do more edits if we need to.

**Pull request merged**
