### PR TITLE
[WIP] Add Scope to ECS guide and AMI

### PR DESCRIPTION
**Pull request by 2opremio**

### CODE REVIEW

**Comment by 2opremio** [comment]
@abuehrle @tomwilkie @errordeveloper, please review.

**Comment by 2opremio** [comment]
@abuehrle This shouldn't had been merged before Scope is released (note the WIP tag) 

I reverted it.

**Comment by abuehrle** [comment]
@2opremio when will the release be?

**Comment by 2opremio** [comment]
Hopefully this week.

**Pull request merged**
