### PR TITLE
Update Mesos guide

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by errordeveloper** [comment]
I've had these changes uncommited and untested for a little while, and someone asked on Slack the other day. I've tested this and it works fine.

**Comment by errordeveloper** [comment]
If someone else wishes to re-test it, it's probably still a good idea.

**Comment by errordeveloper** [comment]
@abuehrle are you happy with this?

**Comment by abuehrle** [comment]
Let me have a look and I will give it a test tomorrow. ( working on that cloud formation template at the moment. )

**Comment by abuehrle** [comment]
If you are going to update the file, why don't you figure out a way to not ship the weave script with the file?  Won't one of your "includes" work for that? 

@lukemarsden

**Comment by errordeveloper** [comment]
> If you are going to update the file, why don't you figure out a way to not ship the weave script with the file? 

I deliberately haven't change this here, as it would make the change bigger.

> Won't one of your "includes" work for that?

No. Includes are only for markdown.

**Comment by abuehrle** [comment]
I would not ship the weave script with the file.  It will just get out of date very quickly.

**Comment by errordeveloper** [comment]
@abuehrle Luke and I have discussed this, and it would not make sense to pin some of the dependencies and not pin others. Here we have pinned Mesos packages, so it's makes sense to pin `weave` as well. Also, please note that functionality of example and features shown here do not depend on a recent version. This guide is in maintenance mode, and doesn't adhere to latest best practice, i.e. we will soon replace it with something that uses CNI plugin, demonstrates Scope and uses Socks Shop as the example app. If you are happy with the copy overall, let's just merge and publish it as it is.

**Comment by abuehrle** [comment]
I am just testing this, and weave didn't install properly.

**Comment by abuehrle** [comment]
I won't spend too much time on this, if you are rewriting it, then.

**Comment by errordeveloper** [comment]
> I am just testing this, and weave didn't install properly.

In what way exactly?

**Pull request closed without merging**
