### PR TITLE
Update Docker Machine guide

### PR DESCRIPTION
**Pull request by errordeveloper**
This is basic update to this popular guide, to make sure most visible issue are fixed (like #178).

Please don't get too picky on the details, I think we can get this improved a lot more in many ways, as Docker for Mac and Windows become more stable. Also, the new Swarm features would affect a lot of what's shown here anyway.

@abuehrle please merge and publish ASAP.

### CODE REVIEW

**Comment by rade** [comment]
why do we have a copy of the weave script!?!?

Rest LGTM.

**Comment by errordeveloper** [comment]
> why do we have a copy of the weave script!?!?

That's been discussed over and over, original motivation was to have one less thing for the user to download and check version etc. We have since identified a number of other issue with this approach, and last time @abuehrle was going to make this change, but for some reason the script is still in master. For the purpose of this PR, I've just updated what's there.

**Comment by rade** [comment]
> That's been discussed over and over

#88 and #183.

Anyway, as I said, LGTM.

**Comment by abuehrle** [comment]
@errordeveloper how do I fix the weave script out of the master?   I am not sure how to do that.  I didn't realize that this was one of my tasks.  Still would like to edit this, so don't merge yet.

**Comment by abuehrle** [comment]
BTW: I'm a technical writer.  I don't really update scripts, although I have done so.

**Pull request merged**
